In [1]:
from math import *
import numpy as np

In [2]:
def amplitude_probabilities(a,b):
    import numpy as np 
    import warnings
    warnings.simplefilter("ignore", np.ComplexWarning)
    # if a != np.conj(a):
    a = sqrt((a*np.conj(a)).real)
    # if b != np.conj(b):
    b = sqrt((b*np.conj(b)).real)
    mag = sqrt(a**2 + b**2)
    return a/mag,b/mag, (a/mag)**2,(b/mag)**2

In [3]:
amplitude_probabilities(sqrt(3)/2,sqrt(3)/4 + 1j*1/4)

(0.8660254037844387, 0.5, 0.7500000000000001, 0.25)

In [4]:
amplitude_probabilities(7,3)

(0.9191450300180578,
 0.39391929857916763,
 0.8448275862068964,
 0.15517241379310343)

In [5]:
amplitude_probabilities(9,3)

(0.9486832980505138, 0.31622776601683794, 0.8999999999999999, 0.1)

Single Qubit Gates

In [6]:
Ax = np.array([[0,1],[1,0]])

In [7]:
Az = np.array([[1,0],[0,-1]])

In [8]:
Ah = np.array([[1/sqrt(2),1/sqrt(2)],[1/sqrt(2),-1/sqrt(2)]])

In [9]:
As = np.array([[1,0],[0,1j]])

In [10]:
def Au3(theta,phi,lam):
    a = cos(theta/2)
    b = (cos(lam) - 1j * sin(lam)).real * sin(theta/2)
    c = (cos(phi) + 1j*sin(phi)).real * sin(theta/2)
    d = (cos(phi+lam) - 1j*sin(phi+lam)).real * cos(theta/2)
    return np.array([[a,b],[c,d]])

In [11]:
Au3(pi/7,0,pi)

array([[ 0.97492791, -0.22252093],
       [ 0.22252093, -0.97492791]])

In [12]:
Ah

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

Two Qubit gates

In [13]:
Acx = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

In [14]:
Acz = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,-1]])

In [15]:
As.dot(Ah).dot([0,1])

array([0.70710678+0.j        , 0.        -0.70710678j])

In [16]:
Acz.dot(Acx).dot(np.array([0,0,1,0]))

array([ 0,  0,  0, -1])

Create 2 Qubit pass through gates with Kroneger product of the identity .

In [17]:
Aid = np.array([[1,0],[0,1]])

In [18]:
As2 = np.kron(Aid,As)

In [19]:
Acz.dot(As2)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j]])

In [20]:
Ah2 = np.kron(Ah,Aid)

In [21]:
Ah2

array([[ 0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.70710678],
       [ 0.70710678,  0.        , -0.70710678, -0.        ],
       [ 0.        ,  0.70710678, -0.        , -0.70710678]])

In [22]:
Ah2.dot(Acx).dot([0,0,1,1])

array([ 0.70710678,  0.70710678, -0.70710678, -0.70710678])

Teleportation Circuit

In [116]:
Aloader = Ah2.dot(Acx)

In [117]:
Aloader

array([[ 0.70710678,  0.        ,  0.        ,  0.70710678],
       [ 0.        ,  0.70710678,  0.70710678,  0.        ],
       [ 0.70710678,  0.        ,  0.        , -0.70710678],
       [ 0.        ,  0.70710678, -0.70710678,  0.        ]])

In [2]:
def amplitudes(arry):
    import numpy as np 
    import warnings
    warnings.simplefilter("ignore", np.ComplexWarning)
    return (arry * np.conj(arry)).real


In [3]:
amplitudes([2/5,1j*4/5,1j/5,2/5])

array([0.16, 0.64, 0.04, 0.16])

In [23]:
Ah2.dot(Acx).dot(Ah2)

array([[ 0.5,  0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5,  0.5],
       [ 0.5, -0.5,  0.5,  0.5],
       [-0.5,  0.5,  0.5,  0.5]])

In [26]:
Ahk = np.kron(Ah,Ah)

In [38]:
Axc = np.round(Ahk.dot(Acx).dot(Ahk))

In [39]:
Axc

array([[ 1., -0., -0.,  0.],
       [ 0., -0., -0.,  1.],
       [-0.,  0.,  1., -0.],
       [-0.,  1.,  0., -0.]])

In [40]:
np.round(Ah2.dot(Axc).dot(Ah2))

array([[ 1.,  0., -0.,  0.],
       [ 0.,  1.,  0., -0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.]])